server:
  port: 8881

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    hikari:
      username: root
      password: root


mybatis:
  type-aliases-package: com.example.demo5.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
